<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('TestProj')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('bootstrap.js'), 'text/javascript', array('id' => 'microloader', 'data-app' => '4b5f83cd-0937-447e-ab79-2f2696ef61db'))
        ?>
    </head>
    <body>
<!--    <form name="upload-form" id="upload-form" method="post" enctype="multipart/form-data" action="/archive">
    <div class="form-element">
        <input type="text" name="name">
        <label for="files">Upload</label>
        <input type="file" name="files[]" id="files" multiple="true">
    </div>

    <button>Submit</button>-->
</form>
    </body>
</html>
